# summary agent: generation of summary sections for the final smr report

from langsmith import traceable
from schemas import SMRState, ReportSummary
from utils import convert_smr_state_to_json


class SummaryAgent:
    def __init__(self, model):
        self.model = model

    @traceable(name = 'Summary Agent', run_type = 'chain')
    def run(self, state):

        prompt = f'''
        You are the Summary Agent in a Structured Medication Review (SMR) pipeline.

        ROLE:
        * Generate a concise clinical overview.
        * Generate a final clinical conclusion.
        * Summarise findings produced by previous agents.

        OBJECTIVE:
        * Review the completed SMRState.
        * Review the prioritised findings.
        * Produce a structured summary of the patient's medication review.
        * Summarise medication profile, indications, drug-drug interactions,
          medication-related risks, deprescribing opportunities, monitoring
          requirements and prioritised recommendations.
        * Highlight the most clinically significant findings.
        * Highlight key patient safety concerns.
        * Highlight the highest-priority recommendations.

        INPUT:
        * The current SMRState object.
        * The confirmed findings ranked by clinical priority.

        REASONING GUIDELINES:
        * Use only information contained within the SMRState.
        * Summarise findings already identified by previous agents.
        * Use ranked_findings to determine which findings receive the greatest emphasis.
        * Present critical and high-priority findings before moderate and low-priority findings.
        * Do not give equal emphasis to all findings.
        * If no critical or high-priority findings exist, state this clearly.
        * Do not invent diagnoses, indications, interactions, risks, monitoring requirements,
          deprescribing opportunities or recommendations.
        * Do not introduce information that is not present within the SMRState.
        * Preserve uncertainty where uncertainty exists in the source findings.
        * Do not describe a finding as validated when its validation result failed.
        * Where a stage passed with warnings, preserve the relevant uncertainty.

        CLINICAL SAFETY GUIDELINES:
        * Prioritise patient safety concerns in the summary.
        * Ensure significant risks and high-priority recommendations are clearly communicated.
        * Do not make definitive prescribing decisions.
        * Do not generate new clinical advice.
        * Do not contradict findings generated by previous agents.

        OUTPUT REQUIREMENTS:
        * Return valid JSON only.
        * Follow the supplied schema exactly.
        * Do not return markdown, explanations or reasoning outside the JSON.
        * Do not modify the SMRState.

        OVERVIEW REQUIREMENTS:
        * Provide a concise summary of the patient's medication review.
        * Summarise the key clinical findings.
        * Emphasise the highest-priority confirmed findings.
        * Use professional clinical language.

        CONCLUSION REQUIREMENTS:
        * Provide a concise clinical conclusion.
        * Emphasise the most important risks and recommendations.
        * Preserve uncertainty and acknowledge important validation warnings.

        JSON SCHEMA:
        {ReportSummary.model_json_schema()}

        RANKED FINDINGS:
        {convert_smr_state_to_json(state.ranked_findings)}

        SMR STATE:
        {convert_smr_state_to_json(state)}
        '''

        response = self.model.invoke(prompt)

        raw = (
            response.content
            .replace('```json', '')
            .replace('```', '')
            .strip()
        )

        start = raw.find('{')
        end = raw.rfind('}') + 1

        if start == -1 or end == 0:
            raise ValueError('SUMMARY AGENT DID NOT RETURN A VALID JSON OBJECT.')

        raw = raw[start:end]

        result = ReportSummary.model_validate_json(raw)

        state.overview = result.overview
        state.conclusion = result.conclusion

        return state

# clinician report generation
def generate_clinician_report(state, overview, conclusion):

    report = []

    def value(attribute):
        return attribute if attribute not in [None, ''] else 'NOT RECORDED'

    def priority_value(attribute):
        return attribute.upper() if attribute not in [None, ''] else 'NOT SPECIFIED'

    def validation_status(validation):
        return 'NOT RUN' if validation is None else validation.status.replace('_', ' ').upper()

    def finding_value(finding, field, default = 'NOT RECORDED'):
        value_found = finding.get(field) if isinstance(finding, dict) else getattr(finding, field, None)
        return value_found if value_found not in [None, ''] else default

    report.extend(['-' * 60, 'STRUCTURED MEDICATION REVIEW', '-' * 60])
    report.extend(['OVERVIEW:', overview, '-' * 60])

    report.append('CLINICAL PRIORITIES:')

    if state.ranked_findings:
        for priority_level in ['CRITICAL', 'HIGH', 'MODERATE', 'LOW']:
            findings_for_level = [
                finding
                for finding in state.ranked_findings
                if str(
                    finding_value(
                        finding,
                        'priority_level',
                        ''
                    )
                ).upper() == priority_level
            ]

            if not findings_for_level:
                continue

            report.append(f'\n{priority_level} PRIORITY:')

            for finding in findings_for_level:
                report.append(
                    f'* {finding_value(finding, "description")}')
                report.append(
                    f'  TYPE: {finding_value(finding, "finding_type")}')
                report.append(
                    f'  PRIORITY SCORE: {finding_value(finding, "priority_score")}')
                report.append(
                    f'  SOURCE: {finding_value(finding, "source")}')
    else:
        report.append('NO RANKED CLINICAL FINDINGS AVAILABLE.')

    report.append('-' * 60)

    report.append('PATIENT INFORMATION:')
    report.append(f'PATIENT ID: {state.patient.patient_id}')
    report.append(f'AGE: {state.patient.age}')
    report.append(f'SEX: {state.patient.sex}')
    report.append(f'ETHNICITY: {value(state.patient.ethnicity)}')
    report.append('-' * 60)

    report.append('CLINICAL INFORMATION:')
    report.append(f'WEIGHT: {value(state.patient.weight)}')
    report.append(f'BMI: {value(state.patient.bmi)}')

    report.append('\nLABORATORY RESULTS:')
    report.append(f'SYSTOLIC BP: {value(state.patient.systolic_bp)}')
    report.append(f'DIASTOLIC BP: {value(state.patient.diastolic_bp)}')
    report.append(f'HBA1C LEVEL: {value(state.patient.hba1c)}')
    report.append(f'EGFR LEVEL: {value(state.patient.egfr)}')
    report.append(f'CREATININE LEVEL: {value(state.patient.creatinine)}')
    report.append(f'TOTAL CHOLESTEROL LEVEL: {value(state.patient.total_cholesterol)}')
    report.append(f'LDL CHOLESTEROL LEVEL: {value(state.patient.ldl_cholesterol)}')
    report.append(f'POTASSIUM LEVEL: {value(state.patient.potassium)}')
    report.append(f'HAEMOGLOBIN LEVEL: {value(state.patient.haemoglobin)}')
    report.append(f'SMOKING STATUS: {value(state.patient.smoking_status)}')
    report.append(f'ALCOHOL STATUS: {value(state.patient.alcohol_status)}')
    report.append(f'FRAILTY SCORE: {value(state.patient.frailty_score)}')
    report.append(f'FALLS HISTORY: {value(state.patient.falls_history)}')
    report.append('-' * 60)

    report.append('CONDITIONS:')

    if state.patient.conditions:
        for condition in state.patient.conditions:
            report.append(f'* {condition}')
    else:
        report.append('NO CONDITIONS RECORDED.')

    report.append('-' * 60)

    report.append('CURRENT MEDICATIONS:')

    if state.medications.medications:
        for medication in state.medications.medications:
            report.append(f'* NAME: {medication.name}')
            report.append(f'  DOSE: {value(medication.dose)}')
            report.append(f'  FREQUENCY: {value(medication.frequency)}')
            report.append(f'  ROUTE: {value(medication.route)}')
            report.append(f'  START DATE: {value(medication.start_date)}')
    else:
        report.append('NO MEDICATIONS RECORDED.')

    report.append('-' * 60)

    report.append('INDICATIONS:')

    if state.indications.indications:
        for indication in state.indications.indications:
            report.append(f'* {indication.medication_name}: {indication.indication}')
            report.append(f'  RATIONALE: {indication.rationale}')
            report.append(f'  SOURCE: {value(indication.source)}')
    else:
        report.append('NO INDICATIONS IDENTIFIED.')

    report.append('-' * 60)

    report.append('DRUG-DRUG INTERACTIONS:')

    if state.interactions.interactions:
        for interaction in state.interactions.interactions:
            report.append(f'* {interaction.drug_a.upper()} & {interaction.drug_b.upper()}')
            report.append(f'  SEVERITY: {interaction.severity.upper()}')
            report.append(f'  RATIONALE: {interaction.rationale}')
            report.append(f'  SOURCE: {value(interaction.source)}')
    else:
        report.append('NO INTERACTIONS IDENTIFIED.')

    report.append('-' * 60)

    report.append('RISK ASSESSMENT:')

    if state.risks.risks:
        for risk in state.risks.risks:
            report.append(f'RISK TYPE: {risk.risk_type}')
            report.append(f'SEVERITY: {risk.severity.upper()}')
            report.append(f'RATIONALE: {risk.rationale}')
            report.append(f'SOURCE: {value(risk.source)}')
    else:
        report.append('NO SIGNIFICANT RISKS IDENTIFIED.')

    report.append('-' * 60)

    report.append('DEPRESCRIBING OPPORTUNITIES:')

    if state.deprescribing.deprescribing:
        for medication in state.deprescribing.deprescribing:
            report.append(f'\nMEDICATION: {medication.medication}')
            report.append(f'PRIORITY: {priority_value(medication.priority)}')
            report.append(f'ISSUE: {medication.issue}')
            report.append(f'RATIONALE: {medication.rationale}')
            report.append(f'SUGGESTED ACTION: {medication.suggested_action}')
            report.append(f'SOURCE: {value(medication.source)}')
    else:
        report.append('NO DEPRESCRIBING OPPORTUNITIES IDENTIFIED.')

    report.append('-' * 60)

    report.append('MONITORING REQUIREMENTS:')

    if state.monitoring.monitoring:
        for medication in state.monitoring.monitoring:
            report.append(f'\nMEDICATION/CONDITION: {medication.medication_or_condition}')
            report.append(f'PRIORITY: {priority_value(medication.priority)}')
            report.append(f'MONITORING REQUIRED: {medication.monitoring_required}')
            report.append(f'TIMEFRAME: {value(medication.timeframe)}')
            report.append(f'RATIONALE: {medication.rationale}')
            report.append(f'SOURCE: {value(medication.source)}')
    else:
        report.append('NO MONITORING REQUIREMENTS IDENTIFIED.')

    report.append('-' * 60)

    report.append('RECOMMENDATIONS:')

    if state.recommendations.recommendations:
        for recommendation in state.recommendations.recommendations:
            report.append(f'\nRECOMMENDATION: {recommendation.recommendation}')
            report.append(f'PRIORITY: {priority_value(recommendation.priority)}')
            report.append(f'RATIONALE: {recommendation.rationale}')
            report.append(f'SOURCE: {value(recommendation.source)}')
    else:
        report.append('NO RECOMMENDATIONS GENERATED.')

    report.append('-' * 60)

    report.append('VALIDATION SUMMARY:')

    validation_results = [
        ('MEDICATIONS', state.medications_validation),
        ('INDICATIONS', state.indications_validation),
        ('INTERACTIONS', state.interactions_validation),
        ('RISKS', state.risks_validation),
        ('DEPRESCRIBING', state.deprescribing_validation),
        ('MONITORING', state.monitoring_validation),
        ('RECOMMENDATIONS', state.recommendation_validation),
        ('FINAL', state.final_validation)
    ]

    for stage_name, validation in validation_results:
        report.append(f'{stage_name}: {validation_status(validation)}')

        if validation is not None:

            if validation.summary:
                report.append(f'  SUMMARY: {validation.summary}')

            if validation.issues:
                for issue in validation.issues:
                    report.append(f'  * {issue.severity.upper()}: ')
                    report.append(f'{issue.description}')

    report.append('-' * 60)

    report.append('CONCLUSION:')
    report.append(conclusion)
    report.append('-' * 60)

    return '\n'.join(report)
